### PR TITLE
docs(security): Add warning

### LINKED ISSUE #613: Promotion of unsafe code
Documentation Is:

- [ ] Missing
- [X] Needed
- [X] Confusing
- [ ] Not Sure?

### Please Explain in Detail...

[Content Security Polcies](https://www.w3.org/TR/CSP2/) (CSPs) make the web a safer place. Authors can use unsafe policies, but those are clearly labelled so authors do not use them by accident. One such unsafe policy is `unsafe-inline`.

This loader heavily promotes unsafe-inline code: All available options for `injectType` except for `linkTag` are unsafe, including the default value (`styleTag`). This makes it a barrier for the adoption of tighter CSPs. As this loader is used on a lot of websites, this has a huge impact on the security of the web in general. 

As discussed in #306 and #487, CSPs allow to use nonces for inline code. However, these are not a proper solution. The [spec](https://www.w3.org/TR/CSP3/#security-considerations) is quite clear about the many drawbacks of nonces:

> Using a nonce to allow inline script or style is less secure than not using a nonce, as nonces override the restrictions in the directive in which they are present. An attacker who can gain access to the nonce can execute whatever script they like, whenever they like. That said, nonces provide a substantial improvement over 'unsafe-inline' when layering a content security policy on top of old code. When considering 'unsafe-inline', authors are encouraged to consider nonces (or hashes) instead.

### Your Proposal for Changes

- Change the default inject type to `linkTag`
- Clearly explain the security issues of all other inject types
- Clearly explain the security issues of nonces

### PR DESCRIPTION
**Pull request by xi**
This PR contains a:

- [X] **bugfix**
- [ ] new **feature**
- [ ] **code refactor**
- [ ] **test update** 
- [ ] **typo fix**
- [ ] **metadata update**

### Motivation / Use-Case

Fixes #613

### Breaking Changes

--

### Additional Info

I created these additions based on https://github.com/webpack-contrib/style-loader/issues/613#issuecomment-1843225551 by @alexander-akait. I hope this is what you had in mind.

### CODE REVIEW

**Comment by evenstensberg** [comment]
Could you sign the CLA?

**Review by evenstensberg — COMMENTED** [review]
Looks good. Will LGTM after CLA is signed

**Comment by xi** [comment]
CLA is signed

**Review by evenstensberg — APPROVED** [review]
lgtm

**Comment by xi** [comment]
I fixed the commit message

**Review by alexander-akait — APPROVED** [review]

**Pull request merged**
