### PR TITLE
insertInto and insertAt collaboration bug fixed

### PR DESCRIPTION
**Pull request by Vasikaran**
**What kind of change does this PR introduce?**

Bugfix

**Did you add tests for your changes?**
Yes, added test case too.

**If relevant, did you update the README?**
No need to update README.

**Summary**
When using insertInto ( as a function ) and insertAt (as an object), the compiled code would throw an error in console. In this PR, I've changed source code slightly and without affecting existing workflow. 

An issue I've raised in recent. #313 

**Does this PR introduce a breaking change?**

No. Testing well. And test case also got 100 percentage result.

**Other information**
Hope you will accept my PR ASAP. Casue, we've a recuirement based on this.

### CODE REVIEW

**Comment by evilebottnawi** [comment]
@Vasikaran you should accept CLA

**Comment by Vasikaran** [comment]
@evilebottnawi I've signed in CLA. But the label didn't change. That shows **Not signed yet**

**Comment by evilebottnawi** [comment]
@Vasikaran 
> Vasikaran S seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please add the email address used for this commit to your account.

**Comment by Vasikaran** [comment]
@evilebottnawi I see nothing to add my email address in this commit.

**Comment by evilebottnawi** [comment]
@Vasikaran address in commit is difference what you use for github

**Comment by Vasikaran** [comment]
@evilebottnawi I think finally I did that.

**Comment by evilebottnawi** [comment]
@Vasikaran need second eyes and we can merge

**Comment by Vasikaran** [comment]
@evilebottnawi What did you mean second eyes? I can't understand.

**Comment by Vasikaran** [comment]
@evilebottnawi @ooflorent  Kindly publish this at least as a patch version like 0.21.1. Till now I wasn't able to use this two options at the same time.

**Comment by evilebottnawi** [comment]
@Vasikaran in todo, try to find time today :+1:

**Pull request merged**
