### PR TITLE
Force repaint in Chrome for link elements

### PR DESCRIPTION
**Pull request by aparticka**

### CODE REVIEW

**Comment by michael-ciniawsky** [comment]
@aparticka usecase please and would it only work in Chrome?

**Comment by michael-ciniawsky** [comment]
#121

**Comment by bebraw** [comment]
Please add a comment so people know why the timeout exists.

**Comment by michael-ciniawsky** [comment]
Is the PR already ok the way it is in regard to #121 ? Our is there any detailed work required like add an option to set the delay e.g `options.delay/options.timeout`  in `setTimeOut`?

**Comment by ekulabuhov** [comment]
TBH, I would close this as irrelevant. Too much time passed since the PR was opened. We don't know if the issues is still happening. We don't even know what the issue was to begin with. Doesn't look like anyone else had this issue during that time either.

In relation to #121: I don't see how it could help to solve it as `setTimeout` makes it even more asynchronous then it was.

Are we OK to close this now and re-open if more details emerges in the future?

**Comment by bebraw** [comment]
Ok. Let's close.

@aparticka When you have time, please comment.

**Pull request closed without merging**
