### PR TITLE
fix support server side usage

### PR DESCRIPTION
**Pull request by magalhas**
I'm using local scopes and I wasn't able to render on the server side because of style loader. This little fix solved all my problems :+1:

### CODE REVIEW

**Comment by randycoulman** [comment]
This little fix works great for us as well.  Here's more context on how we're using it: http://randycoulman.com/blog/2016/03/22/testing-with-mocha-and-webpack/ (reference to this issue at the very end, under `Gotchas`).

**Comment by sokra** [comment]
see last section in this chapter: https://github.com/webpack/css-loader#local-scope

use `css/locals` when using SSR.

**Comment by magalhas** [comment]
@sokra does that work if I don't use ExtractTextPlugin and rely on shipping my CSS inside JS? I'm asking because with the PR it worked perfectly, I guess the `css/locals` solution will as well, just want to be sure of it :)

**Comment by sokra** [comment]
`css/locals` just returns the local to class mappings, without style tags, CSS and such stuff, which is not needed for server-side rendering. It works CSS inside JS, but that is usually not used in combination with server-side rendering because you either get FOUC or blocking JS.

**Comment by magalhas** [comment]
I was asking for development. Thank you for clarifying!

**Comment by sokra** [comment]
> I was asking for development.

Then it's fine of course... ;)

**Comment by peterh32** [comment]
So... this never got merged? And style-loader is still broken for server-side rendering?

**Comment by evilebottnawi** [comment]
@peterh32 style-loader works good with SSR. Please don't write about your problem in old closed issue,
create a new issue with description and minimally reproducible test repo. Thanks!

**Comment by alsun** [comment]
It look like in 1.0.0 it's come back :cry:

**Comment by evilebottnawi** [comment]
@alsun no

**Pull request closed without merging**
