### PR TITLE
Make urls absolute in blob

### PR DESCRIPTION
**Pull request by Strate**
Related #93

### CODE REVIEW

**Comment by Strate** [comment]
Soo?

**Comment by unimonkiez** [comment]
Give this man a cookie!

**Comment by oller** [comment]
Wooo, so does this PR give us full source maps with relative path assets, without the need for an absolute `publicPath`.

:clap:

**Comment by Strate** [comment]
@oller sure. Tested by using in real project, works like a charm.

**Comment by sergeylukin** [comment]
Worked for me at first glance. Any reason why this isn't merged?
@Strate I suggest squashing commits into one

**Comment by v3lbloud** [comment]
Thanks for the patch. Works like charm.

**Comment by Strate** [comment]
@sokra this is really helpful patch, as you can see. could you merge it? Or maybe I could somehow improve this patch?

**Comment by geekyme** [comment]
bump. Need this patch

**Comment by vperron** [comment]
Come on, please merge :)

**Comment by oller** [comment]
Pleeeeaaase! 🎁

**Comment by tizmagik** [comment]
It's been 5 months... Is there any reason for this not to be merged @sokra ?

**Comment by sokra** [comment]
yes. This is not a good solution. It should be solved on CSS AST. It's better to solve it before the style loader in the css loader

**Comment by codisms** [comment]
@sokra I can't find any code in css-loader that is client side, which is where this logic would need to reside so it knows the browser location at run time.  Can you point us in the right direction?

**Comment by bendytree** [comment]
@Strate great idea and great work!

I just submitted a very similar pull request which is opt-in via a `style?fixUrls` flag and has some unit tests to verify the behavior since I'm not parsing the CSS into an AST.

Anyone feel free to fork [bendytree/style-loader](https://github.com/bendytree/style-loader) and then use a git url in your package.json:

    ...
    "style-loader": "git+https://git@github.com/YOUR_USERNAME/style-loader.git",
    ...

**Comment by tizmagik** [comment]
@sokra any guidance you could provide @Strate / @bendytree et al to solve this properly in the CSS AST as you suggested?

**Comment by Strate** [comment]
As for me, use css ast on client side would be an overkill. This patch used in real world project since it's creation without any problem. With keeping in mind that it used only in dev environment, I could say that it has sufficient quality to merge.

**Comment by SpearThruster** [comment]
This is a huge issue on my project as well, can we get update why this hasn't been merged?

**Comment by motleydev** [comment]
Adding an additional, please. Or at least provide feedback how this could be made better.

**Comment by SimonSelg** [comment]
I'll work on this this afternoon. I have some ideas how to solve this correctly on AST level. But I'll have to test the performance impact.

**Comment by Strate** [comment]
**Attention please**.

I've found a solution for the problem without patching this loader.
Just add following line on the top of your topmost entry:
```
__webpack_public_path__ = window.location.protocol + "//" + window.location.host + "/"
```
This line modifies `output.publicPath` option at browser runtime, adding current protocol and host. If you have a custom publicPath, just add it to the end of prefix.
This solution requires you to have no `output.publicPath` specified in config or command line.
If you need to pass publicPath from command line or webpack configuration file you can use environmant variables together with `DefinePlugin`:

```js
// webpack.config.js

module.exports = {
  pluginns: [
    new webpack.DefinePlugin({
      'process.env.WEBPACK_PUBLIC_PATH': JSON.stringify(process.env.WEBPACK_PUBLIC_PATH)
    })
  ]
}

// topmostEntryPoint.js
__webpack_public_path__ = window.location.protocol + "//" + window.location.host + "/" + process.env.WEBPACK_PUBLIC_PATH;
```

and run build with command:
```
WEBPACK_PUBLIC_PATH="your/public/path/" webpack
```

**Comment by SpearThruster** [comment]
@Strate your latest solution doesn't work for me sadly. If I log in runtime the '__webpack_public_path__' I get the correct value but the url properties in css (originally scss) aren't updated. Anyone having this issue?

**Comment by SpearThruster** [comment]
So it's still the css source map issues. The latest workaround by @Strate works at my machine ONLY if I disable source maps. The original pull request works for both scenarios.

**Comment by ledil** [comment]
any news on that ?

**Comment by Strate** [comment]
@SpearThruster, try this:
1. Move you code, which augments `__webpack_public_path__` into separate file, which do only that thing. Call it, for example, `bootstrap-public-path.js`.
2. Add it as your first topmost entrypoint in your webpack configuration:
```
entry: [
  "bootstrap-public-path",
  "index" // your old index entrypoint here
]
```
3. Ensure, that your `webpack.config.js` does not set `publicPath` option.

**Comment by IAMtheIAM** [comment]
@Strate Thank you! This did the trick for me to get the paths to resolve correctly inside my SCSS file. I used it for loading fonts in scss, when the scss file is a "blob://" rather than an inline style. 

```
// topmostEntryPoint.js
__webpack_public_path__ = window.location.protocol + "//" + window.location.host + "/" + process.env.WEBPACK_PUBLIC_PATH;```

**Comment by d3viant0ne** [comment]
Also - There were compliance issues we needed to clear up before the CLA bot could be enabled, that was cleared up about 10 days ago.

To get the CLA signed, you just need to close this PR & open it again. That will trigger the CLA workflow again which should allow you to sign it.

Please note, before you close & open it again ensure the email in your local git config matches what you have configured in github.

**Comment by ekulabuhov** [comment]
I looks like this PR might be superseded by #124?

**Comment by d3viant0ne** [comment]
Yes. My take on all of this would be to land #124, put #165 in the next major & close #96 but that plan needs to be confirmed by the @webpack-contrib/org-maintainers

**Comment by bebraw** [comment]
@d3viant0ne Yeah, sounds fine.

**Comment by Strate** [comment]
@d3viant0ne have you read this comment: https://github.com/webpack-contrib/style-loader/pull/96#issuecomment-228370602? This is how I solve this issue current in my project. I think it is enougth to move this trick to README.

**Comment by d3viant0ne** [comment]
It's workaround vs. fix where the workaround is only effective in some cases. This is an issue that needs to be resolved in code

**Comment by michael-ciniawsky** [comment]
#186 (#124) landed, is this the PR still relevant then? If @Strate please close and reopen to trigger the CLA Bot again and rebase against current master, otherwise if you lost interest in this PR in general / #186 (#124) solved the issue please confirm we can close

**Comment by d3viant0ne** [comment]
screen shot 2017-03-16 at 8 38 29 pm

This should be closed in favor of #124 which has already been merged.

**Pull request closed without merging**
