### PR TITLE
Fixed typo 'doom' to 'DOM' in README.md

### PR DESCRIPTION
**Pull request by edave64**
This PR contains a:

- [ ] **bugfix**
- [ ] new **feature**
- [ ] **code refactor**
- [ ] **test update** 
- [X] **typo fix**
- [ ] **metadata update**

### Motivation / Use-Case

"Doom" might be applicable to some aspects of the DOM specifications, but I don't think this was intended as some sort of commentary.

I originally spotted the typo on: https://webpack.js.org/loaders/style-loader/

### Breaking Changes

N/A

### Additional Info

N/A

### CODE REVIEW

**Comment by evilebottnawi** [comment]
Please accept CLA

**Comment by edave64** [comment]
@evilebottnawi Done

**Comment by evilebottnawi** [comment]
Can you regenerate lock file? Just remove `package-lock.json` and run `npm i` to avoid npm audit problems

**Comment by edave64** [comment]
@evilebottnawi That seems to have fixed the audit.

**Comment by evilebottnawi** [comment]
Thanks!

**Pull request merged**
