### PR TITLE
changed property access for ES3 compatibility

### PR DESCRIPTION
**Pull request by sungkang**
**What kind of change does this PR introduce?**
Fixed an ES3 compatibility bug when accessing a property named "default".

**Did you add tests for your changes?**
No, but ran the existing tests that covered that functionality.

**If relevant, did you update the README?**
No

**Summary**
This was causing a backwards compatibility issue for applications running in IE8. The "default" property was accessed using dot notation and was changed to using square bracket notation.
Issue: https://github.com/webpack-contrib/style-loader/issues/362

**Does this PR introduce a breaking change?**
No

### CODE REVIEW

**Comment by evilebottnawi** [comment]
@sungkang please fix CI error

**Comment by sungkang** [comment]
attempted to resolve the CI error, it first seems to be related to the Node Security Platform service shutting down and nsp check being no longer is valid.
I have resolved all the vulnerabilities from the npm audit check, but it's failing now because the Dockerfile in the CircleCI 2.0 base build container is using node version 8.11.1 which has npm5, which doesn't have the audit command. Changing that to version 10 I suppose will resolve this issue.

**Comment by evilebottnawi** [comment]
Close in favor https://github.com/webpack-contrib/style-loader/pull/390

**Comment by evilebottnawi** [comment]
Anyway thanks for PR

**Pull request closed without merging**
