### PR TITLE
Fixed negative refs

### PR DESCRIPTION
**Pull request by tomasAlabes**
Style should be able to be injected if `unuse` was called more times than `use`.

```
myCss.use()
myCss.unuse()
myCss.unuse()

myCss.use() //should be valid, regardless of the double call to unuse
```

Following the GC idea, there are not "negative" amount of references, just none. Preventing adding more refs makes no sense.
This basically prevents `refs` from being negative, then the behavior is the same as before.

### CODE REVIEW

**Comment by tomasAlabes** [comment]
@sokra any feedback on this?
Thanks

**Comment by bebraw** [comment]
I would say #176 needs to go in first. After that adding a test for this PR would be possible. 👍

**Comment by bebraw** [comment]
Alright. #176 is in. Please add a test and we'll merge.

**Comment by tomasAlabes** [comment]
@bebraw test is in place. I ran it without my change and it failed, with my change 🚀 
Thanks for your work in the loaders guys!

**Pull request merged**
