### PR TITLE
Export locals if they are available and not on .use()

### PR DESCRIPTION
**Pull request by cusspvz**
`style/useable` should match the usual expected behavior and export locals even if the styles aren't being used.

On SSR, `use` will throw an error, and you will never be able to access locals.
Please give priority to this. Thanks.

### CODE REVIEW

**Comment by NekR** [comment]
+1 to this. Another way (if you don't want expose `locals` immediately) could be this:

```
exports.use = function() {
  // ...
  return content.locals;
}
```

**Comment by cusspvz** [comment]
@NekR I think you should have always access to locals, because that's the default behavior on others. My on my use case, I'm using React and created a React decorator that calls `.use()` and `.unuse()` whenever a component is mounted or unmounted. So far so good, until I tried to do it Isomorphically and on the server-side, styles are never used, which means it doesn't have `locals` and it doesn't attribute the right classes on the render.

I had to change the style-loader by hand and include it on my project until this is merged.

**Comment by cusspvz** [comment]
ping @sokra

**Comment by NekR** [comment]
@cusspvz Yeah, I agree. I am currently using your solution too. Hope it'll be merged.

**Comment by cusspvz** [comment]
I'm releasing a boilerplate that needs this fix.
Any chance of have it merged?

Also, tried to sign cla license and it seems this repo is not registered yet.
captura de ecra 2017-01-29 as 19 36 10

**Comment by SpaceK33z** [comment]
@cusspvz we're having some issues regarding the CLA at the moment, it probably doesn't like that we moved this repo from webpack to webpack-contrib. You can sign the CLA here: https://cla.js.foundation/webpack/webpack. Sorry for the troubles.

**Comment by cusspvz** [comment]
@SpaceK33z done!

Yeah, I've also tried with `webpack-contrib` instead before but I wasn't successful. Thanks.

**Comment by d3viant0ne** [comment]
@cusspvz - There were compliance issues we needed to clear up before the CLA bot could be enabled, that was cleared up about 10 days ago.

To get the CLA signed, you just need to close this PR & open it again. That will trigger the CLA workflow again which should allow you to sign it.

Please note, before you close & open it again ensure the email in your local git config matches what you have configured in github.

**Comment by cusspvz** [comment]
Done!

**Comment by michael-ciniawsky** [comment]
@cusspvz Thx 👍

**Pull request merged**
