### PR TITLE
Add href replace option.

### PR DESCRIPTION
**Pull request by danielverejan**
**What kind of change does this PR introduce?**
Feature: replace href attribute of the <link> that points to the required stylesheet.

**Did you add tests for your changes?**
No tests

**If relevant, did you update the README?**
Updated the README to include the replace option but it may need additional input.

**Summary**
In short: it works similar as the url option, the difference is that it look for the `<link>` that has a reference to the required stylesheet instead of creating one.

I'm working on a .Net project where the views are Razor template, so no options there to use InterpolateHtmlPlugin because the views are static. Nor I can use the style-loader with or without the url option for dynamic style loading(HMR) as the view references are static to. By static references I mean that ex: the `<link rel="stylesheet" href="Build/css/index.css">` is used in DEV and PROD environments.

**Does this PR introduce a breaking change?**
No breaking changes.

### CODE REVIEW

**Comment by michael-ciniawsky** [comment]
@danielverejan I'm in favour of the feature, but not of the implementation tbh :). But also no idea how to do it atm

@bebraw @d3viant0ne @ekulabuhov  Any ideas ? 😛

**Comment by d3viant0ne** [comment]
Code diving aside, there is a valid need though I question the scope of this particular features usefulness within the scope of style-loader. It's a pretty niche requirement

**Comment by bebraw** [comment]
I agree with @d3viant0ne. This might work better as a loader of its own. Given how the code has been written, that would not be an issue.

**Comment by ekulabuhov** [comment]
Similar opinion. The code is very specific to this particular problem. @danielverejan would it work for you if you moved it into a separate loader and then chain it as usual?

**Comment by michael-ciniawsky** [comment]
Yep a seperate package e.g `link-loader` is an option

**Comment by bebraw** [comment]
Do you think `link-loader` could live below contrib? I can set up a repo based on **webpack-defaults** and invite Daniel there.

**Comment by d3viant0ne** [comment]
That is the path I would suggest.

**Comment by bebraw** [comment]
Only problem - [link-loader](https://www.npmjs.com/package/link-loader) is taken.

@danielverejan Suggest a name available at npm and I'll set you up.

Time to close this PR. 👍

**Comment by michael-ciniawsky** [comment]
Accepting under webpack-contrib would be even better, very nice 😛 

ahhh...npm naming, maybe even ask the owner to choose another name for his package :D

**Comment by danielverejan** [comment]
Thanks for the many responses.
@michael-ciniawsky  I have at work a version with some miner improvements like `querySelector` and would be happy to get any suggestion for further  improvements.

@d3viant0ne  Working on a .Net project, before webpack I have used browser-sync which has basically this feature, it's called there something like *style injection*. Being forced to use a plain `<style>` tag for dev and prod this was very useful. That's what I have been missing when I moved to webpack with style-loader.

I'll come in with a name shortly, thanks for the opportunity!

**Comment by danielverejan** [comment]
@bebraw Maybe some of these?

restyle-loader
relink-loader
css-link-loader

**Comment by bebraw** [comment]
@danielverejan Sure. Pick the one you like the most and I'll set you up. 👍

**Comment by danielverejan** [comment]
restyle-loader

**Comment by bebraw** [comment]
@danielverejan Done. I set up that follows **webpack-defaults** setup. You'll have to fill in meta and publish. Add me and @d3viant0ne as npm project owners (`npm owner add`) after you have published something. 👍

**Comment by danielverejan** [comment]
ok, thanks!

**Pull request closed without merging**
