### PR TITLE
refactor: webpack defaults

### PR DESCRIPTION
**Pull request by evilebottnawi**
webpack defaults

/cc @hiroppy friendly ping, here PR how we should update loaders/plugins

### CODE REVIEW

**Comment by evilebottnawi** [comment]
Anyway after merge we need refactor code and tests

**Comment by evilebottnawi** [comment]
Also we need fix coverage problem in test

**Comment by hiroppy** [comment]
@evilebottnawi Thanks!

IMO: I think it would be difficult to track all plugins / loaders when the webpack-default's changes. I felt it would be easier to manage configuration files etc. collectively using monorepo like lerna.

**Comment by evilebottnawi** [comment]
@hiroppy yep, anyway update webpack-defaults should be done on major release or if something buggy, in other cases we can avoid this update

**Comment by hiroppy** [comment]
@evilebottnawi DO you plan to refactor other loaders/plugins using webpack-default?

**Comment by evilebottnawi** [comment]
@hiroppy only when are we going to make major release

**Comment by hiroppy** [comment]
ok, thanks

**Pull request merged**
