### PR TITLE
Support only Node 6 or higher

### PR DESCRIPTION
**Pull request by hiroppy**
**What kind of change does this PR introduce?**

refactor, chore

**Did you add tests for your changes?**

no 

**If relevant, did you update the README?**

no(only automatic correction by prettier)

**Summary**

- Remove Mocha and Add Jest.
- Upgrade jsdom.
- Add husky, lint-staged.
- Add Prettier, eslint.

I refactor(e.g. `var` -> `const` or `let`) only tests not lib.

**Does this PR introduce a breaking change?**

Maybe no because CI doesn't check Node0.12.0 from before.

**Other information**

### CODE REVIEW

**Comment by evilebottnawi** [comment]
@hiroppy we use `webpack-default` (https://github.com/webpack-contrib/webpack-defaults) for loader/plugin and other stuff, it gives us contain identical configuration between projects, for using need update @webpack-contrib/defaults package and run npm run defaults

**Comment by hiroppy** [comment]
@evilebottnawi You mean should we use webpack-default to replace existing code?

**Comment by evilebottnawi** [comment]
@hiroppy it is boilerplate for us configuration, i can send pr to demonstrate that this

**Comment by hiroppy** [comment]
Could you send pr to demonstrate that this?

**Comment by evilebottnawi** [comment]
@hiroppy webpack-default already have prettier, we should use this boilerplate as standard for our projects to avoid difference configuration between our repos, and yes all new feature should be implemented in webpack-default and then updated in repos, i am open to new features, in Monday i will update webpack-default here, so you can see how i do this and do same in other repos

**Comment by hiroppy** [comment]
@evilebottnawi ok, so I'll close this pr.

**Pull request closed without merging**
