### PR TITLE
chore(package): add `package-lock.json` (npm@5)

### PR DESCRIPTION
**Pull request by michael-ciniawsky**
**What kind of change does this PR introduce?**

 Chore

**Did you add tests for your changes?**

✅ 

**Summary**

- Add `package-lock.json` (` >= npm@5`)

### CODE REVIEW

**Comment by evilebottnawi** [comment]
@michael-ciniawsky It seems to me a bit early to do it

**Comment by michael-ciniawsky** [comment]
Yep, not urgent at all

**Comment by d3viant0ne** [comment]
This is actually an issue we need to discuss at the org level. i.e. Use npm || use yarn and then update `webpack-defaults` accordingly. Not really necessary, no prudent to keep both given I have seen dependency version related issues crop up with the differences with how they both work.

In either case, we should probably give `node@v8.0.0 / npm@5.0.0` a few weeks in the wild before we pick on or the other.

**Comment by michael-ciniawsky** [comment]
https://github.com/webpack-contrib/organization/issues/13

**Pull request closed without merging**
