### PR TITLE
Add shadow-DOM option type for injectType

### PR DESCRIPTION
**Pull request by Justinidlerz**
This PR contains a:
- [x] new **feature**

### Motivation / Use-Case
Extract styles and put into a container, then can injected into the shadow-DOM conainer
```js
import component from 'component';
import getCss from 'style-loader/dist/runtime/injectStyleInScript';

class MyElement extends Element {
    constructor() {
        super();
        const shadowContent = this.attachShadow({ mode: 'open' });  
        const style = document.createElement('style');
        style.innerHTML = getCss();
        shadowContent.appendChild(style);
    }
}

### CODE REVIEW

**Review by alexander-akait — CHANGES_REQUESTED** [review]
Wrong solution, you don't need `style-loader` in this case, just use `css-loader` and use `toString()` from returned content

**Comment by alexander-akait** [comment]
run `css.toString()`

**Comment by alexander-akait** [comment]
https://github.com/webpack-contrib/css-loader/blob/master/src/runtime/api.js#L11

**Comment by Justinidlerz** [comment]
@alexander-akait  So you mean I can use that see like: 

```tsx
import Main from 'components';
import {render} from 'react-dom'
import allCss from 'css-loader/dist/runtime/api';

class MyElement extends Element {
    constructor() {
        super();
        const shadowContent = this.attachShadow({ mode: 'open' });  
        const style = document.createElement('style');
        style.innerHTML = allCss.toString(); // This one?
        shadowContent.appendChild(style);
        const root = document.createElement('div');
        shadowContent.appendChild(root);

        render(<Main />, root);
    }
}
```

**Comment by alexander-akait** [comment]
No, just use:
```js
import Main from 'components';
import {render} from 'react-dom'
import styles from './style.css';

class MyElement extends Element {
    constructor() {
        super();
        const shadowContent = this.attachShadow({ mode: 'open' });  
        const style = document.createElement('style');
        style.innerHTML = styles.toString();
        shadowContent.appendChild(style);
        const root = document.createElement('div');
        shadowContent.appendChild(root);

        render(<Main />, root);
    }
}
```

**Comment by Justinidlerz** [comment]
@alexander-akait  Sorry, I don't quite understand the method of use you proposed
Could you please give me an example of how to use the `css-loader` to getting the combined styles?

**Comment by alexander-akait** [comment]
Example above

**Comment by alexander-akait** [comment]
Just remove `style-loader`, you don't need this

**Comment by Justinidlerz** [comment]
> No, just use:
> 
> ```js
> import Main from 'components';
> import {render} from 'react-dom'
> import styles from './style.css';
> 
> class MyElement extends Element {
>     constructor() {
>         super();
>         const shadowContent = this.attachShadow({ mode: 'open' });  
>         const style = document.createElement('style');
>         style.innerHTML = styles.toString();
>         shadowContent.appendChild(style);
>         const root = document.createElement('div');
>         shadowContent.appendChild(root);
> 
>         render(<Main />, root);
>     }
> }
> ```

I can import the root CSS file see like your provided case. But how to apply nested component styles?

**Comment by alexander-akait** [comment]
Sorry, it is not QA services, please use stackoverflow for questions and personal help, we don't need this API, because `css-loader` provide your ability to use `toString` and return string of CSS, it is enough for your case

**Comment by Justinidlerz** [comment]
**/a/component.tsx**
```jsx
import css from './style.css'

const A = () => {
   return <div />
}

export default A;
```

**/b/component.tsx**
```jsx
import css from './style.css'
import A from '../a/component'

const B = () => {
   return <div>
       <A />
   </div>
}
export component;
```

> There have many components...

**main.tsx**

```tsx
import B from 'b/component';
import {render} from 'react-dom'
import getCss from 'style-loader/dist/runtime/injectStyleInScript';

class MyElement extends Element {
    constructor() {
        super();
        const shadowContent = this.attachShadow({ mode: 'open' });  
        const style = document.createElement('style');
        style.innerHTML = getCss();
        shadowContent.appendChild(style);
        const root = document.createElement('div');
        shadowContent.appendChild(root);

        render(<Main />, root);
    }
}
```

**Comment by alexander-akait** [comment]
You don't need this API, what is not clear from my answer? Remove `style-loader` and don't use this, you don't need this for custom components.

**Comment by alexander-akait** [comment]
You mix multiple react component with the one custom component, this is the wrong approach to what you are trying to achieve

**Pull request closed without merging**
