### PR TITLE
Style custom dev

### PR DESCRIPTION
**Pull request by babyhuangshiming**
This PR contains a:

- [ ] **bugfix**
- [ ] new **feature**
- [ ] **code refactor**
- [ ] **test update** 
- [ ] **typo fix**
- [ ] **metadata update**

### CODE REVIEW

**Comment by evilebottnawi** [comment]
Thanks, we don't need it

**Comment by mahaina** [comment]
> Thanks, we don't need it

hi @evilebottnawi, this PR relatives to [issue-462](https://github.com/webpack-contrib/style-loader/issues/462).
or is there any other approaches? thank u

**Comment by evilebottnawi** [comment]
@mahaina we need discussion before send a PR

**Comment by mahaina** [comment]
> @mahaina we need discussion before send a PR

hi @evilebottnawi we build [issue-462](https://github.com/webpack-contrib/style-loader/issues/462).

**Pull request closed without merging**
