### PR TITLE
Added unit tests for basic configurations

### PR DESCRIPTION
**Pull request by ekulabuhov**
**What kind of change does this PR introduce?**
Build related change

**Did you add tests for your changes?**
Yes

**If relevant, did you update the README?**
Not relevant

**Summary**
This PR introduces unit testing setup we can use to check for regressions when adding new features to style-loader. Hopefully, this can provide a base for PR authors to test against. 

The setup consists of: 
* [memory-fs](https://github.com/webpack/memory-fs) to avoid writing to file system and to collocate input files
* [jsdom](https://github.com/tmpvar/jsdom) to provide lightweight DOM implementation

Each test is running fully setup webpack compiler. This allows for great level of flexibility. Included are 5 tests for basic configurations shown in the Readme file.

**Does this PR introduce a breaking change?**
No

**Other information**

### CODE REVIEW

**Comment by d3viant0ne** [comment]
@ekulabuhov - This is no longer a required check and is not `blocking` this pull request. As i said in slack, all of it's complaints are invalidated the second we apply `webpack-defaults` anyway nor is codacy.com our hosted static analysis tooling of choice.

**Comment by d3viant0ne** [comment]
@ekulabuhov - one thing of note.

If we are going to add tests and i'm all for it, best to do it in a way that is beneficial for all future pull requests.

- Mocha || Jest + Chai ( if an assertion lib is necessary )
- Grab the `webpac-contrib` standard travis file
- Webpack dependency from devDep => peerDep (Travis installs this)

**Comment by ekulabuhov** [comment]
@d3viant0ne I've tried moving webpack to peerDep but it didn't install it on Travis: https://travis-ci.org/ekulabuhov/style-loader/jobs/206042662

Other than that, I think I'm ok with merging this.

**Comment by d3viant0ne** [comment]
Requires, the full travis file. 

```
sudo: false
language: node_js
branches:
  only:
    - master
matrix:
  fast_finish: true
  include:
    # - os: linux
    #   node_js: '7'
    #   env: WEBPACK_VERSION="2.2.0" BITHOUND_CHECK=true JOB_PART=lint
    - os: linux
      node_js: '7'
      env: WEBPACK_VERSION="2.2.0" JOB_PART=test
    - os: linux
      node_js: '4.3'
      env: WEBPACK_VERSION="2.2.0" JOB_PART=test
    - os: linux
      node_js: '6'
      env: WEBPACK_VERSION="2.2.0" JOB_PART=test
    # - os: linux
    #   node_js: '7'
    #   env: WEBPACK_VERSION="2.2.0" JOB_PART=coverage
before_install:
  - nvm --version
  - node --version
before_script:
  - if [ "$WEBPACK_VERSION" ]; then yarn add webpack@^$WEBPACK_VERSION; fi
  # - if [ "$BITHOUND_CHECK" ]; then npm install -g bithound; bithound check git@github.com:$TRAVIS_REPO_SLUG.git; fi
script:
  - yarn run travis:$JOB_PART
after_success:
  - bash <(curl -s https://codecov.io/bash)
```

**Comment by d3viant0ne** [comment]
@ekulabuhov - I've enabled `style-loader` in travis-ci.org. Should run next time anything changes.

**Comment by d3viant0ne** [comment]
`.gitattributes`

```
# Treats the lock file as binary & prevents conflict hell
yarn.lock -diff
```

**Comment by ekulabuhov** [comment]
@d3viant0ne - I've tried moving webpack to peerDependencies again. I can see it working in Travis (where it explicitly install it), but it fails when running mocha locally. Both NPM and yarn seem to ignore peerDependencies. Wouldn't it require each developer to install it manually?

**Comment by bebraw** [comment]
I know from experience that npm 2 will be problematic with `peerDependencies`. It would not be a big problem for me if we pushed `webpack` to `devDependencies` too to make to get this merged. 👍

**Comment by d3viant0ne** [comment]
At the moment we are only testing against a single version of webpack. We have the same issue in less-loader, `devDep` for the time being is fine.

**Comment by bebraw** [comment]
Ah, yeah. I see your point now. Basically you want to test against multiple versions of webpack later on. That's a good separate problem to solve.

**Comment by ekulabuhov** [comment]
Ok, thanks! Fixed Node v4 issues. Changed travis.yml from v4.3 to v4 to capture latests version of node. Got tests passing on all 3 versions. Good to go 👍

**Comment by d3viant0ne** [comment]
That was actually `4.3` for a reason (Minimum supported nodejs version for Webpack).

**Comment by ekulabuhov** [comment]
Ah, ok, didn't think about that. Looked at css-loader and it's set to v4.7.

**Comment by d3viant0ne** [comment]
I'll update it. At one point the minimum version was 4.7 ( long story )

**Comment by d3viant0ne** [comment]
@bebraw - Unless @ekulabuhov has something else he wants to add to this, i'd say ship it.

Trying to kill that Codacy PR check with fire, for the time being just ignore it.

**Comment by ekulabuhov** [comment]
I'm happy to merge this. But it will definately break: https://github.com/webpack-contrib/style-loader/pull/122

**Comment by d3viant0ne** [comment]
Pull request validations > any code fix imo. Ship it :)

**Comment by bebraw** [comment]
👍 Nice work.

**Comment by michael-ciniawsky** [comment]
👍

**Pull request merged**
